### ISSUE TITLE
Installation failure on OS X in Canopy venv 

### ISSUE THREAD

**Issue by jonmoore** [jupyter-incubator/dashboards#145]
When trying to install to a fresh venv, created with canopy_cli venv from the current Canopy (1.6.1) and populated only with the latest pip, setuptools and jupyter, I get the following error:

```
    Enabling extension for notebook
    Installing notebook server extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gx/sztl1j9j4z31t2knck5qxjl40000gn/T/pip-build-8drASU/jupyter-dashboards/setup.py", line 66, in <module>
        'install': InstallCommand
      File "/Applications/Canopy.app/appdata/canopy-1.6.1.3253.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Applications/Canopy.app/appdata/canopy-1.6.1.3253.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Applications/Canopy.app/appdata/canopy-1.6.1.3253.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/gx/sztl1j9j4z31t2knck5qxjl40000gn/T/pip-build-8drASU/jupyter-dashboards/setup.py", line 34, in run
        fn = os.path.join(cm.profile_dir, 'ipython_notebook_config.py')
    AttributeError: 'ConfigManager' object has no attribute 'profile_dir'
```

**Comment by parente** [comment]
The latest stable release (jupyter_dashboards 0.1.0) is only compatible with IPython Notebook 3.2.x. We're going to cut a 0.2.0 release of the extension this week which is Jupyter Notebook 4.0.x compatible. 

Did you pip install from pypi or from the master branch source tree?

**Comment by parente** [comment]
Version 0.2.0 of the extension is now out and compatible with 4.0.x of Jupyter Notebook.

**Comment by jonmoore** [comment]
Thanks, I hadn't noticed the version requirement in 0.1.0, and 0.2.0 is working now for me with Jupyter 4.0.x.
